# Generated by Django 3.2.9 on 2021-12-04 13:44

import accounts.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('complement', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('perfil_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_perfil_image)),
            ],
        ),
    ]
